# Generated by Django 3.2.12 on 2023-08-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_expiry_date',
            field=models.DateField(null=True, verbose_name='Membership Expiry Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=10, null=True, verbose_name='Membership Type'),
        ),
    ]
