# Generated by Django 3.2.12 on 2023-08-22 10:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=accounts.models.generate_otp, max_length=4),
        ),
    ]
