# Generated by Django 3.2.12 on 2023-08-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otprequest_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprequest',
            name='channel',
        ),
    ]
