# Generated by Django 3.2.12 on 2023-08-31 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230831_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 14, 10, 39, 766506)),
        ),
    ]
