# Generated by Django 3.2.12 on 2023-08-31 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otprequest_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 15, 16, 7, 354557, tzinfo=utc)),
        ),
    ]
